name: Generate sample APK

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-18.04


    steps:

      - uses: actions/checkout@v3

      - name: Use Java11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug apk
        run: ./gradlew clean assembleDebug

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create Release and Upload APK
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Sample ${{ steps.get_version.outputs.VERSION }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: sample.apk
          asset_content_type: application/zip